// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:2ba262dd-f38a-4806-a1cb-f0e860d82b86",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_ZqEhk5bGr",
    "aws_user_pools_web_client_id": "6p2sqfb4fco8hffagrd22u5mbn",
    "oauth": {}
};


export default awsmobile;
